2020-08-05 14:51:59,498 -- CRITICAL -- в файле config_client_log.py -- в строке 24 -- Критическая ошибка
2020-08-05 14:51:59,498 -- ERROR -- в файле config_client_log.py -- в строке 25 -- Ошибка
2020-08-05 14:53:14,747 -- CRITICAL -- в файле config_client_log.py -- в строке 22 -- Критическая ошибка
2020-08-05 14:53:14,747 -- ERROR -- в файле config_client_log.py -- в строке 23 -- Ошибка
2020-08-05 14:56:09,355 -- CRITICAL -- в файле config_client_log.py -- в строке 22 -- Критическая ошибка
2020-08-05 14:56:09,355 -- ERROR -- в файле config_client_log.py -- в строке 23 -- Ошибка
2020-08-05 14:56:09,356 -- DEBUG -- в файле config_client_log.py -- в строке 24 -- Отладочная информация
2020-08-05 14:56:09,356 -- INFO -- в файле config_client_log.py -- в строке 25 -- Информационное сообщение
2020-08-05 15:49:54,218 -- DEBUG -- в файле client.py -- в строке 70 -- Используемся адрес 127.0.0.1 и порт 7777 по умолчанию
2020-08-05 15:49:54,219 -- DEBUG -- в файле client.py -- в строке 31 -- Сгенерирован запрос с сообщением presence для Guest
2020-08-05 15:49:54,219 -- INFO -- в файле client.py -- в строке 42 -- Получен код от сервера 200
2020-08-05 15:49:54,219 -- DEBUG -- в файле client.py -- в строке 44 -- Отправлено - 200 : OK
2020-08-05 15:49:54,219 -- INFO -- в файле client.py -- в строке 83 -- Получен ответ от сервера 200 : OK
2020-08-05 15:52:07,302 -- DEBUG -- в файле client.py -- в строке 70 -- Используемся адрес 127.0.0.1 и порт 7777 по умолчанию
2020-08-05 15:52:07,303 -- DEBUG -- в файле client.py -- в строке 31 -- Сгенерирован запрос с сообщением presence для Guest
2020-08-05 15:52:07,304 -- INFO -- в файле client.py -- в строке 42 -- Получен код от сервера 200
2020-08-05 15:52:07,304 -- DEBUG -- в файле client.py -- в строке 44 -- Отправлено - 200 : OK
2020-08-05 15:52:07,304 -- INFO -- в файле client.py -- в строке 83 -- Получен ответ от сервера 200 : OK
2020-08-05 15:55:31,388 -- CRITICAL -- в файле config_client_log.py -- в строке 22 -- Критическая ошибка
2020-08-05 15:55:31,388 -- ERROR -- в файле config_client_log.py -- в строке 23 -- Ошибка
2020-08-05 15:55:31,388 -- DEBUG -- в файле config_client_log.py -- в строке 24 -- Отладочная информация
2020-08-05 15:55:31,388 -- INFO -- в файле config_client_log.py -- в строке 25 -- Информационное сообщение
2020-08-05 15:55:39,601 -- DEBUG -- в файле client.py -- в строке 70 -- Используемся адрес 127.0.0.1 и порт 7777 по умолчанию
2020-08-05 15:55:39,602 -- DEBUG -- в файле client.py -- в строке 31 -- Сгенерирован запрос с сообщением presence для Guest
2020-08-05 15:55:39,603 -- INFO -- в файле client.py -- в строке 42 -- Получен код от сервера 200
2020-08-05 15:55:39,603 -- DEBUG -- в файле client.py -- в строке 44 -- Отправлено - 200 : OK
2020-08-05 15:55:39,603 -- INFO -- в файле client.py -- в строке 83 -- Получен ответ от сервера 200 : OK
2020-08-05 15:58:38,058 -- DEBUG -- в файле client.py -- в строке 70 -- Используемся адрес 127.0.0.1 и порт 7777 по умолчанию
2020-08-05 15:58:38,058 -- DEBUG -- в файле client.py -- в строке 31 -- Сгенерирован запрос с сообщением presence для Guest
2020-08-05 15:58:38,058 -- DEBUG -- в файле client.py -- в строке 80 -- Отправили сообщение {'action': 'presence', 'time': 1596635918.058995, 'user': {'account_name': 'Guest'}} на сервер
2020-08-05 15:58:38,058 -- INFO -- в файле client.py -- в строке 42 -- Получен код от сервера 200
2020-08-05 15:58:38,058 -- DEBUG -- в файле client.py -- в строке 44 -- Отправлено - 200 : OK
2020-08-05 15:58:38,058 -- INFO -- в файле client.py -- в строке 83 -- Получен ответ от сервера 200 : OK
